
public class Nicknames
{
    public static string[] _nicknames =
        {
        "FrozenHeart",
        "ShadowKiller",
        "Darkness",
        "BloodySniper",
        "LoneWolf",
        "DragonSlayer",
        "BoneCrusher",
        "GhostRider",
        "KillerInstinct",
        "RapidFire",
        "Terminator",
        "InfiniteAmmo",
        "DeathDealer",
        "SilentAssassin",
        "Predator",
        "TerminatorX",
        "TheLegendKiller",
        "MegaDeathDealer",
        "FrostBite",
        "ShadowAssassin",
        "Reaper",
        "GrimReaper",
        "DeathBringer",
        "ReaperJustice",
        "Reckoning",
        "DeathBringerofJustice",
        "BloodyAssassin",
        "TimeStopper",
        "uperAssassin",
        "MuffinMan",
        "Legolas",
        "Littleboy1234",
        "Deathstroke",
        "Assassin",
        "Masterchief",
        "Sniper",
        "Terminator",
        "Predator",
        "Batman",
        "Superman",
        "Wonderwoman",
        "IronMan",
        "Flash",
        "Spiderman",
        "Bulletproof",
        "Clockwerk",
        "EyeTiger",
        "LionHeart",
        "LoneWolf",
        "NoMercy",
        "PrecisionAiming",
        "Rampage",
        "SniperAssassin",
        "SuperMario",
        "TerminatorPrime",
        "ToxicAvenger",
        "MachinegunMama",
        "Vengeance",
        "ZombieKiller",
        "Maverick",
        "OmegaMan",
        "GrimReaper",
        "Bloodbath",
        "Butcher",
        "Dreadnaught",
        "Executioner",
        "Frostmourne",
        "Ghostblade",
        "Godfather",
        "Grimlock",
        "Goliath",
        "Juggerwroth",
        "KillerInstinct",
        "Maimerino",
        "PhantomAssassin",
        "MortalKombat",
        "Godlike",
        "Nightmare",
        "Hulk",
        "IronMan",
        "JediKnight",
        "MasterChief",
        "Ninja",
        "RoboCop",
        "Thor",
        "Wolverine",
        "Paladin",
        "Butcher",
        "BloodyMary",
        "Reaper",
        "VladImpaler",
        "Werewolf",
        "Magician",
        "PeterPan",
        "CaptainJackSparrow",
        "RobinHood",
        "ThorinOakenshield",
        "Shrek",
        "Smeagle",
        "RedBaron",
        "DarthVadar",
        "Penguin",
        "Hulk",
        "Superman",
        "Batman",
        "IronMan",
        "Spiderman",
        "Flash",
        "Executioner",
        "Ninja",
        "SamuraiBob",
        "KillerClowns",
        "ZombieHunter",
        "ZidaneTribal",
        "LichKing",
        "Templar",
        "Shadowsmith",
        "EvilKitty",
        "ElBanditoMuerto",
        "WinniePuuh",
        "JackRipper",
        "Wolfman",
        "Dracula",
        "FrankensteinsMonster",
        "LordRings",
        "Dragon",
        "Thief",
        "Knight",
        "Sophia",
        "Bloody Mary",
        "Deathbringer",
        "Valkyrie",
        "Berserker Babe",
        "Crusher Queen",
        "Maiden of Pain",
        "Lady Death",
        "Diamond Girl",
        "Demon Spawn",
        "Phantom Lady",
        "Frosty the Snowwoman",
        "Grim Reaper",
        "Killer Kitten",
        "Lethal Lolita",
        "Nuclear Winter",
        "Pirate Princess",
        "Queen of Carnage",
        "Reaper Queen",
        "Sorceress Supreme",
        "Terminatrix",
        "Warrior Princess",
        "Witchblade",
        "Adorabella",
        "KittyKatGaming",
        "TootsieRoll",
        "LadyKing",
        "Princess",
        "Empress",
        "Queen",
        "Destroyer",
        "Midnight",
        "Lone Wolf",
        "Valkyrie",
        "Lara Croft",
        "Katniss",
        "Arya Stark",
        "Hermione Granger",
        "Elizabeth Bennet",
        "Daenerys Targaryen",
        "Black Widow",
        "Wonder Woman",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "1331",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "1331",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "1331",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "413x31",
        "Noob Slayer",
        "Godlike DotA",
        "Kill Master",
        "Pwnerer",
        "Badass Gamer",
        "The One And Only",
        "King Of Games",
        "Game Changer",
        "Unbeatable Ninja",
        "Worthy Gamer",
        "Destroyer Of Worlds",
        "Ultimate Pwn Machine",
        "Demigod Slayer",
        "The Best Of All Time",
        "The Flash",
        "Mean And Nasty",
        "Master Of Destruction",
        "The Destroyer",
        "The Immortal",
        "The Great One",
        "Titan Of Games",
        "Superior Gamer",
        "Invincible Beast",
        "Lord Of The Games",
        "Unstoppable Gamer",
        "The Ultimate Player",
        "Infamous Slayer",
        "Unparalleled Grandmaster",
        "Immortal Master",
        "Undefeatable Slayer",
        "The Greatest Of All Time",
        "Unbeaten God",
        "Godlike Gamer",
        "Perfect Player",
        "Indestructible Beast",
        "Overlord of Games",
        "Demon Slayer",
        "Immortal Gamer",
        "Superhuman Gamer",
        "Undefeatable",
        "Best Player Ever",
        "Number One Gamer",
        "Undefeated King Of Games",
        "Kill Machine",
        "Unstoppable Force",
        "Unstoppable Godlike",
        "Overlord Slayer/Giver of Noobs",
        "Master Gamer",
        "Baddest Bitch",
        "Ultimate Gamer",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "Grimmy bear",
        "Rising Star",
        "Savage Wolf",
        "Daredevil",
        "Nightmare",
        "Thunder Storm",
        "Shadow Hunter",
        "Dragon Tamer",
        "Master of Shadows",
        "Redemption",
        "Death Knight",
        "Fantasma",
        "Dark Slayer",
        "Shadow Assassin",
        "Blood Mage",
        "Stone Heart",
        "Legendary Hero",
        "Ancient Guardian",
        "Epic Warrior",
        "DragonLord",
        "Phoenix Fire",
        "Grim Reaper",
        "Warrior Goddess",
        "Gladiator King",
        "The Angel Of Death",
        "Eclipse",
        "Nova",
        "Phoenix",
        "Infinite",
        "Crystal",
        "Lightning Strike",
        "Destruction",
        "Agent Smith",
        "Kitten McGrady",
        "Sir Lancelot",
        "Princess Fiona",
        "Darth Vader",
        "Aurora",
        "Blizzard",
        "Bane",
        "Crystal",
        "Diamond",
        "Dragon",
        "Ember",
        "Frostfire",
        "Gale",
        "Inferno",
        "Goofy Gopher",
"Angry Bird",
"Bob the Builder",
"Captain Underpants",
"Darth Vader",
"Dora the Explorer",
"KillMeNowPlease",
"Lazy Lizard",
"Scaredy Cat",
"Screaming Sheep",
"Stinky Feet",
"System Debt",
"Ewok",
"Frozen Elsa",
"Goku",
"Harry Potter",
"Iron Man",
"Jedi Master Yoda",
"Kanye West",
"Mario",
"Minecraft Steve",
"Crazy Cat Lady",
"Darth Vader",
"Elvis Presley",
"Grumpy Old Man",
"Harry Potter",
"Indiana Jones",
"Jedi Master",
"Lara Croft",
"Darth Vader",
"Elmo",
"Frozen Elsa",
"Hulk Hogan",
"Iron Man",
"Jedi Master",
"Mario",
"Minecraft Steve",
"Nyan Cat",
"Pacman",
"Pikachu",
"Plumber",
"Fish Slap",
"Taco Bell",
"Butterfly Knife",
"Doritos Locos Taco",
"Spicy Chicken Bites",
"Pizza",
"Cupcake",
"Sour Patch Kids",
"Cheetos",
"Skittles",
"Goldfish Crackers",
"Lemonheads",
            "The John Cena's",
"The Green Team",
"The Rockets",
"The Captain Crunch",
"The Undertakers",
"The Assassins",
"The Bobcats",
"The 49ers",
"The Celtics",
"The Lakers",
"The Bulls",
"The Spurs",
"The Heat",
"The Timberwolves",
"The Grizzlies",
"The Nuggets",
"The Thunder",
"The Kings",
"The Mavericks",
"The Warriors",
"The Wizards",
"The Trail Blazers",
"The Clippers",
"The Pacers",
"The Pistons",
"The Knicks",
"The Hawks",
"The Hornets",
"The Raptors",
"The Suns",
"The Sharks",
"The Miami Vice",
"The Houston Rockets",
"The Los Angeles Lakers",
"The Golden State Warriors",
"The Chicago Bulls",
"The San Antonio Spurs",
"The Boston Celtics",
"The Detroit Pistons",
"The Philadelphia 76ers",
"The Oklahoma City Thunder",
"The Utah Jazz",
"The Portland Trail Blazers",
"The Toronto Raptors",
"The Denver Nuggets",
"The Charlotte Hornets",
"Clan Coco",
"The Deathly Hollows",
"The Fellowship of the Ring",
"The Night's Watch",
"House Stark",
"House Lannister",
"House Targaryen",
"House Baratheon",
"The Golden Company",
"Stormborn Warriors",
"House Sand",
"The Unsullied",
"House Arryn",
"House Tyrell",
"Clan Scarface",
"Clan Cobra",
"Clan Python",
"The Warriors of the North",
"The Dothraki",
"House Greyjoy",
"House Martell",
"Dragon Riders of Berk",
"The Jedi",
"The Sith",
"The Autobots",
"The Decepticons",
"Galactic Republic",
"Separatist Alliance",
"House Stark",
"Red Team Alpha",
"Blue Team Bravo",
"Black Ops Delta Force",
"Team Awesome Sauce",
"Gaming For Ever Afters",
"The Underdogs",
"Immortal Gamers",
"Noobs Unite",
"The Prodigies",
"Phoenix Reborn Clan",
"Rare Breed",
"The Savages",
"Seekers of the Lost Clan",
"Titans Gaming",
"Unstoppable Force",
"Vortex Gaming",
"Warriors of the Dark",
"The Wolf Pack",
"X-treme Gamers",
"Zombie Killers Clan",
"Ace",
"Cutiepie",
"Chris",
"Rokkstar",
"Daredevil",
"Dragon",
"Freakshow",
"Gunslinger",
"Iceman",
"Jedi",
"Kingpin",
"Laserbrain",
"Maverick",
"Neptune",
"Nighthawk",
"Rambo",
"Shadow",
"Titan",
"Trigger",
"Viking",
"Warrior",
"Zombie",
"Bear",
"Bulldog",
"Demon",
"Fox",
"Goliath",
"Hawk",
"Hunter",
"Panthera",
"Ravage",
"Scorpion",
"Toadstool",
"Wolverine",
"Xena",
"Zulu",
"Foxy Lady",
"Wolverine",
"Zeus",
"Zorro",
"Shawty",
"33rd",
"Snickers",
"Lil bro",
"Dope boy/girl",
"Bloodbath",
"Chicken Dinner",
"Dying Light",
"Final Circle",
"FUBAR",
"Night Terrorist",
"One Shot, One Kill",
"Out of Ammo",
"Red Zone",
"Sniper Elite",
"The Hunted",
"The Last Stand",
"Toxic Waste",
"Win or Lose",
"Game Over Man",
"Gasoline Cowboy",
"Get Rekt",
"Snipper Expert",
"Walking Dead",
"War Zone",
"You Died",
"You're Fired!",
"Escape from Tarkov",
"Battle Royale",
"Last Man Standing",
"Survival of the Fittest",
"Zero Hour",
"Tiger Shark",
"Gone in 60 Seconds",
"Gun Show",
"Loot Maniacs",
"Mercenary Squad",
"My Bad!",
"No Scope Nubz",
"I'm Outta Here",
"Just Die Already",
"King of the Kill",
"Loot Train",
"Lucky Number Seven",
"Making It Rain",
"No Fun Allowed",
"One in the Chamber",
"Stupendous",
"Awesome Aces",
"Pro Players",
"Legendary",
"Baddies",
"Super Stupendous Team",
"Supa Dupa Duo",
"The Great and Powerful",
"The Dynamic Duo",
"Out of this World",
"Incredible Two",
"Imaginative One",
"The Creative Team",
"The Best Friends",
"The Dream Team",
"The Phenomenal Pair",
"The Dynamic Duo of Doom!",
"Panda and Bamboo",
"Tigers and Pandas",
"Fire and Ice",
"The Perfect Pair",
"The Dynamic Duo of Awesomeness",
"Rock, Paper, Scissors",
"Mario and Luigi",
"Peach and Daisy",
"Yoshi and Birdo",
"Kirby and King Dedede",
"Pikachu and Jigglypuff",
"Charizard and Squirtle",
"Wario and Waluigi",
"The Powerpuff Girls",
"Batman and Robin",
"Harley Quinn and Poison Ivy",
"Iron Man and Captain America",
"Wonder Woman and Aquaman",
"Spiderman and Venom",
"The Avengers",
"Thor and Loki",
"Black Widow and Hawkeye",
"Doctor Strange and Wong",
"Maximus Firestorm",
"Taiga Shiverwind",
"Infinite Darkness",
"The Destroyer",
"Death Bringer",
"The Reaper",
"Valkyrie",
"Shadowblade",
"Dracula",
"Vampire Lord",
"The Grim Reaper",
"Zombie Killer",
"The Butcher",
"Hannibal King",
"The Cannibal",
"The Terminator",
"Alien Slayer",
"Rambo",
"John Rambo",
"King Kong",
"Tarzan",
"Iron Man",
"The Hulkster",
"The Punisher",
"Blood Thirster",
"Blood Demon",
"Blood God",
"The Devil",
"The Immortal",
"Smaug the Dragon Lord",
"The Barbarian",
"King Slayer",
"The Amazon",
"The Hitman",
"The Demon",
"The Warlock",
"Warlord of Hell",
"Nightmare",
"Hellfire",
"Sorrowful Angel of Death",
"Nightshade Shadowstrike",
"Aerotheurge Mistwalker",
"Dreadnaught Tidalwave",
"Stormlord Thunderfury",
"Ragnarok the Destructor",
"The Great Devourer",
"            Feather",
"Flame",
"Orbit",
"Aura",
"Vortex",
"Blaze",
"Infinity",
"Zen",
"Echo",
"Nova",
"Tsunami",
"Sunset",
"Storm",
"Windy",
"Ash",
"Brave",
"Gale",
"Kracken",
"Blade",
"Fallen",
"Bane",
"Dragon",
"Fury",
"Shark",
"Savage",
"Thorn",
"Shine",
"Shadow",
"Hawk",
"Razor",
"River",
"Rock",
"Spirit",
"Steel",
"Tiger",
"Warrior",
"Waves",
"Wolf",
"Zenith",
"            Brutal Bob",
"Raging Randy",
"Killer Ken",
"Psycho Paul",
"Nasty Nick",
"Twisted Tom",
"Doomguy",
"Toxic Tom",
"Dirty Dan",
"Savage Sam",
"Inferno Jake",
"Murder Mike",
"Bloody Mary",
"Demon Dave",
"Vicious Vince",
"Wicked Willy",
"Sinister Steve",
"Nasty Nate",
"Psycho Pete",
"Devilish Dan",
"Hellish Harry",
"Murderous Margie",
"Terrifying Terry",
"Bane Brian",
"Nuclear Neil",
"Sinister Sid",
"Killer Kevin",
"Punishing Pat",
"Toxic Timmy",
"Lethal Lee",
"Nasty Nick",
"Ruthless Richie",
"Furious Frank",
"Maniacal Mark",
"Massive Matt",
"Vicious Victor",
"Angry Andy",
"Savage Steve",
"The Nameless One",
"Butcher",
"Slaughter",
"Terminator",
"Savage Sam",
"1337Hax0r",
"The Killer",
"Superman",
"            Grumpy Gamer",
"Gamer Girl",
"Ninja Gamer",
"Nerd God",
"Shy Gamer",
"Gangsta Gamer",
"Handsome Gamer",
"Butterfly Ninja",
"Indie Game Freak",
"Pixelated Princess",
"Queen of the Games",
"Retro Gamer",
"Savage Gamer",
"Super Smarty Pants Gamer",
"Tomboy Gamer",
"Ultra Geeky Gamer",
"Wiseguy Gamer",
"Gamer Chick",
"Gamer Dude",
"Rage Gamer",
"Game Master",
"Gemini Gamers",
"Pumpkin Spice Latte",
"Ninja Turtles",
"The Avengers",
"The Dark Knight",
"Wonder Woman",
"Superman",
"Spiderman",
"Captain America",
"Iron Man",
"Thor",
"Black Widow",
"Assassin's Creed",
"            Tenacious",
"Epicness",
"Pwnage",
"Skillz",
"Badassery",
"Unstoppable",
"Never Die",
"Legendary",
"Invincible",
"Excellence",
"Mvp",
"Monster Kill",
"Champion",
"Beast Mode On",
"No Mercy",
"God Mode",
"Beasts Unite",
"Immortal",
"Invincible Army",
"The Elite",
"Supreme Ruler",
"Master of the Universe",
"Omnipotent",
"Savior of the World",
"Prince of Darkness",
"King of Hell",
"Lord of the Underworld",
"Omniscient",
"Ice Cold Killer",
"Wicked Sick",
"King Slayer",
"Godlike",
"Ninja",
"Godly",
"Legend",
"            Techno Wizard",
"Dashing Rogue",
"Savage Warlord",
"Fierce Warrior",
"Dragon Slayer",
"Final Boss",
"Legend of the West",
"Master of Arms",
"The Great One",
"King of the North",
"The Lone Wolf",
"The Rising Sun",
"The Shaman of Death",
"The Sorceress",
"The Archmage",
"The Noble Lord",
"The White Knight",
"Dark Warden",
"Doom Bringer",
"God of the Battlefield",
"Lord of the Night",
"The Great Dragon",
"The Titan",
"The Immortal",
"Eternal Champion",
"Champion of the Gods",
"Master of Elements",
"Destroyer of Worlds",
"The Mad God",
"The Immortal King",
"The Phoenix",
"Lord of the Skies",
"Sorceress of Shadows",
"The Visitor",
"Shadow Assassin",
"Unstoppable Samurai",
"The Beast Slayer",
"Lone Sniper",
"Unicorn of Doom",
"Quick Silver",
"Mystic Guardian of the Forest",
"Soul Reaper",
"Unbreakable Firebrand",
"The Empress of Ice and Snow",
"Lone Sniper",
"King Kano",
"Lord Commander",
"Steel Blade",
"Raven of the Night",
"Time Walker",
"Final Frontier",
"Eagle Eye",
"Dragon Heart",
"The Burning One",
"Storm Chaser",
"Shadow Warrior",
"Ice Spike",
"True Guardian",
"Golden Sun",
"The Phoenix Reborn",
"Lightning Flash",
"Ancient Warlord",
"Sun Child",
"Web Slinger",
"Seeker of the Skies",
"Legendary Guardian",
"The Swift One",
"Tiger of the Jungle",
"Storm Rider",
"The Dark Slayer",
"Dragon Lord",
"Free Spirit",
"Charlie",
"Topper",
"Smokey",
"Bandit",
"Speedy",
"Spitfire",
"Bulletproof",
"Delta",
"Foxtrot",
"David",
"Tango",
"Sharky",
"Bam Bam",
"Dynamite",
"Dragon Breath",
"Bloody Mary",
"Smokey Joe",
"Wolf Man",
"Boomerang",
"Hungryforks",
"Instantkarma",
"Lights Out",
"Frozenflame",
"Morphin",
"Teeqo",
"Legendary",
"Impervious",
"vUnbreakable",
"Kitty",
"Jinxed",
"Dancingqueen",
"Midnightglow",
"Pyroclastic Flow",
"Frostbite",
"The Ice King",
"The Ice Queen",
"vFrozen Prince",
"Big Bertha",
"Baby Ace",
"Candy Cane",
"Gunner",
"Kitty Kat",
"Lucky Strike",
"TNT",
"Smokey",
"Volcano",
"Lava Lamp",
"Hot Stuff",
"Fireball",
"Godfather",
"The Destroyer",
"The Terminator",
"Savage",
"Unstoppable",
"Invincible",
"Mastermind",
"The Great Onev",
"The Big Show",
"The War Machine",
"The Hulkv",
"The Beast",
"Dragon Slayer",
"Master of Destruction",
"The Godfather of Destruction",
"Lord of War",
"Spartan Warrior",
"Merciless Killer",
"Ruthless Assassin",
"The Undefeated",
"Immortal",
"Invincible Warrior",
"Conqueror of All",
"Destroyer of Worlds",
"The Conqueror",
"The Chosen One",
"Apex Predator",
"Ultimate Executioner",
"The Conqueror of Worlds",
"Godlike Killer",
"The Immortal Slayer",
"Undefeatable Fighter",
        };
}
